# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------
Qt += gui core widgets xlsx
TEMPLATE = app
TARGET = CustomFlowOrgnz
DESTDIR = ../CustomParamComponent/x64/Debug
CONFIG += debug
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += ./GeneratedFiles
RCC_DIR += ./GeneratedFiles
include(CustomFlowOrgnz.pri)
win32:RC_FILE = CustomFlowOrgnz.rc
